### PR TITLE
Fix - fill inside loop

### PR DESCRIPTION
**Pull request by VojtechPetru**
Tests for https://github.com/EmilStenstrom/django-components/issues/272.

I'll add a couple more tests, just opening the PR early as [instructed](https://github.com/EmilStenstrom/django-components/issues/272#issuecomment-1517803292) by @lemontheme.

### CODE REVIEW

**Comment by VojtechPetru** [comment]
@lemontheme I've added a few more tests based on how I think this feature should work. Please let me know if you think some of them are wrong or if you think more should be added.
One interesting thing I've noticed is, that when I added [a template default](https://github.com/EmilStenstrom/django-components/pull/273/commits/33718cad4915a1ab4f7bff24132c87df05d0bcb1#diff-de6dd17dd65717f14a7d8c1ac50cbaca0e9b5df00b19f56e0419435684147b0eR5), the [basic test](https://github.com/EmilStenstrom/django-components/pull/273/files#diff-adcf9fe4cc76d2f1a251e2ebda2d83aeb360d03c02a24b781d996d7d082aa631R1121) went green, although the slot is overridden in the test.

**Comment by lemontheme** [comment]
Whoops, that last rebase wasn't 100% intentional. Wanted to see how hard it would be to rebase on the branch of PR #269, since there is some interaction between that and what I'll need to implement here. I was expecting to get a confirmation dialog before it actually rebased. Oh well... it just rebased on master. No harm in that.

Annnyway, thanks @VojtechPetru! I still need to take a closer look at it, but at first glance everything looks good. My only remark atm is that I'm seeing the variable name 'objects' in a lot of places, which isn't as informative as I'd personally like. That said, many of our test cases are pretty abstract, so it's probably fine.

I've been experimenting with two different approaches to getting this functionality to work again. Neither is too complex but I'm aiming to keep the rendering logic understandable. Give me a day or so and I'll have it ready ;)

**Comment by VojtechPetru** [comment]
No worries @lemontheme, I can absolutely understand :slightly_smiling_face:

**Comment by VojtechPetru** [comment]
Hello @lemontheme, can I somehow assist you further with resolving this issue?

**Comment by lemontheme** [comment]
Not for the time being. I'll give a quick update, just so you know where we're currently at.

So, basically, I've had to rethink several core assumptions in the slot filling implementation. That work is closely related to #269. Merging that PR in its current state would have spelled trouble for this PR. So I had to go back to the drawing board, iterating on about 6 different approaches until last week I found one that works and is relatively elegant. The implementation of the winning approach is complete, except for a few failing tests which I still need to address.

For now our PR here is blocked on #269. Some of the changes were far-reaching and the commits are messy, so I imagine code review will take a few days/week. Once it's merged, this PR can be rebased and we should see your tests succeed as well. That's the idea at least.

Anyway, sorry it's taking longer than usual. Been juggling quit a few big life changes lately, meaning less energy in the evenings to get stuff done. Nonetheless, I'm hoping to wrap up the implementation side of things in the next few days.

**Comment by EmilStenstrom** [comment]
@lemontheme Thanks for the update! ⭐ 

Don't feel bad for not giving more of your free time to this project. It's IS a hobby project, nothing more, nothing less. I'd rather have you finding a stable but slower pace that works in the long run, than rushing things and compromising on the rest of your life. You don't owe us anything! 🤗

**Comment by VojtechPetru** [comment]
Oh, for sure I agree! I'm not in a rush to have this resolved, just wanted to offer my help in case you'd have a use for it. Sorry if it sounded different. Thanks for the update. :slightly_smiling_face:

**Comment by lemontheme** [comment]
Check it. Green ticks across the board. Tests look good to me[^1].

Thanks for the kind words last week. You're all good. No-one came off as impatient or entitled or anything. The standard I personally hold myself to has just been harder to maintain lately. Probably time for some self-reflection if anything. =p 

[1]: (One of these days, I or someone else is going to have pull on our protective sewage suit and really clean up the entire test suite, but that day is not today.)

**Pull request merged**
