### PR TITLE
Missing context variables and kwargs in component_block

### PR DESCRIPTION
**Pull request by rbeard0330**
These changes address both issues referenced in #16.  Happy to explain any changes or make any further edits you think appropriate.

### CODE REVIEW

**Review by EmilStenstrom — CHANGES_REQUESTED** [review]
These changes look great! The only change I'd like to see is that the tests for this are separate from the rest of the tests. I'm trying hard to really use unit tests in this project, so that each test only tests one specific thing. Would you mind moving the tests to a separate test class with specific templates just for this?

**Comment by rbeard0330** [comment]
Will do!

**Comment by rbeard0330** [comment]
I updated the tests in the last two commits.  I also made an additional substantive change to pass extra_context to Component.render() in one place where it wasn't being passed.

**Comment by EmilStenstrom** [comment]
Looks great, thanks for helping me make django-components better! :) And let me know if you encounter any additional roadblocks or annoyances.

**Pull request merged**
