### PR TITLE
feat(docs): add `startcomponent` docs to the `README.md` file

### PR DESCRIPTION
**Pull request by hanifbirgani**
related #323

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
This is great! The only thing I'm missing is changing the default usage in the topmost tutorial to use the new command instead of directing people to create files themselves. Separate PR och part of this one?

**Comment by hanifbirgani** [comment]
> This is great! The only thing I'm missing is changing the default usage in the topmost tutorial to use the new command instead of directing people to create files themselves. Separate PR or part of this one?

So, do you mean moving the management command section above the "Create your first component" section?

**Comment by EmilStenstrom** [comment]
No, I think the section you've written is great. But it's more like reference docs. The tutorial is "type this to get started", and currently that part is just assuming that people will create files in the right locations. Switching to your new command as the way to get started will make things so much easier!

**Comment by hanifbirgani** [comment]
> No, I think the section you've written is great. But it's more like reference docs. The tutorial is "type this to get started", and currently that part is just assuming that people will create files in the right locations. Switching to your new command as the way to get started will make things so much easier!

I prefer a separate PR for that part.

**Pull request merged**
