### PR TITLE
Issue loading media when RENDER_DEPENDENCIES True

### PR DESCRIPTION
**Pull request by rafae56038**
image
I have an issue, using COMPONENTS = {"RENDER_DEPENDENCIES": True} in settings, specific error is response["Content-Type"], this issue is for media loading.

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
Looks good, thanks for writing up a PR. Currently this is missing a test. Would you mind adding one? Just so we accidental don't remove that code in the future.

**Comment by EmilStenstrom** [comment]
ping @rafae56038

**Comment by EmilStenstrom** [comment]
ping @rafae56038

**Comment by hjalves** [comment]
Can I work on this? I also stumbled on this issue.

**Comment by EmilStenstrom** [comment]
@hjalves Would be much appreciated!

**Pull request merged**
