### PR TITLE
Use wheel in tests, adopt src layout

### PR DESCRIPTION
**Pull request by GabDug**
Partial proposition for #405 

- Use a `src` layout
  - This removes issues when both the installed package (in the venv) and the source code are present, and share the same package name
  - Using explicit package association (fix an issue where the wheel contains the `tests.components` module, see in the [inspector](https://inspector.pypi.io/project/django-components/0.61/packages/58/47/2c17307f20b25c1e0a6ee4beedda141184cc33dcb84a56d2f080ba979eaf/django_components-0.61-py3-none-any.whl/tests/components/__init__.py))
  - This should not be an issue as `django-components` is used a library
- Make tox use the wheel
- Make linters ignore the `build` directory

References:
- https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/
- https://www.b-list.org/weblog/2023/dec/15/python-packaging-src-layout/

I hope this can help resolve the issue, or move the conversation forward :) 

have a great day!

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
Again: Great addition! Very happy to accept more patches that improve how we package and distribute this library.

I should have merged these two in the other order, because now there are merge conflicts, sorry... :)

**Comment by GabDug** [comment]
No issue, I can rebase :)

**Comment by EmilStenstrom** [comment]
@GabDug Excellent :) 

Waiting for feedback from @JuroOravec, if he's OK i'll merge!

**Comment by JuroOravec** [comment]
Again, apologies for the silence, I appreciate how quickly both of you handled this!

**Pull request merged**
