### PR TITLE
Testing pre-commit.ci service

### PR DESCRIPTION
**Pull request by hanifbirgani**
Add a new line to .pre-commit-config.yaml to test pre-commit.ci service in a new pr﻿. related #36

### CODE REVIEW

**Comment by hanifbirgani** [comment]
It worked and changed (formatted) so many files. There are still some unused imports that raise flake8 warnings.

**Comment by EmilStenstrom** [comment]
Hmm... So the checks fail even after auto fixes? Isn't that strange? I'll make a separate commit to run black, isort and flake8 on all the existing code in a couple of days, and they we can try again. Need to close the other open PR too, so it doesn't get stuck in merge hell. Thank you again for setting this up, it will be great!

**Comment by hanifbirgani** [comment]
isort and black have a conflict on line lengths, I try to fix it.

**Comment by hanifbirgani** [comment]
@EmilStenstrom 
I think it's working now, and this PR could be merged.

**Comment by EmilStenstrom** [comment]
@hanifbirgani I just managed to merge the other open PR. I think we need to rerun the auto-fixes to resolve the conflicts. What's the easiest way to get that done?

**Comment by EmilStenstrom** [comment]
Or let me know if you want me to make a try. I think we could delete the auto-fix commit, and force-push this branch?

**Comment by hanifbirgani** [comment]
@EmilStenstrom 
I did the force push, and it worked.

**Comment by EmilStenstrom** [comment]
@hanifbirgani Really appreciate your work. Would you like to come on as a core committer for django-components? Send an e-mail to emil@emilstenstrom.se and lets talk more!

**Pull request merged**
