### PR TITLE
Fix for #239

### LINKED ISSUE #239: Very problematic behavior after upgrading to 0.26.1
I've got a simple component named card. Here's the template 

```html
<div class="card mb-3 {{ color }} {{ border_color }}">
  <h5 class="card-header {{ header_color }} {{ header_text_color }}">
    {{ title }}</h5>

  <div class="card-body {{ color }} {{ text_color }}">
    {% slot "body" %}{% endslot %}
  </div>
</div>
```

and the function:

```py
@component.register("card")
class Card(component.Component):
    template_name = "components/card.html"

    # This component takes one parameter, a date string to show in the template
    def get_context_data(  # noqa PLR0913
        self, title, color="", text_color="", header_color="", header_text_color="", border_color=""
    ):
        return {
            "title": title,
            "color": color,
            "text-color": text_color,
            "header_color": header_color,
            "header_text_color": header_text_color,
            "border_color": border_color,
        }

    class Media:
        css = ""
        js = ""
```

Now, this was working flawlessly when I was using {% slot %} to render my template. However, after I upgraded to the new version and used {% fill %} instead it works *only* when I *include* a partial template with component on my template! 

So, Let's suppose I have a template named foo.html and I want to include this component:

```
{% component_block "card" "Test"  %}
{% fill "body" %}
  <div>test</div>
{% endfill %}
{% endcomponent_block %}
```

If I add this *directly* on foo.html I'll get the following error:

```
Traceback (most recent call last):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django_extensions\management\technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loader_tags.py", line 294, in do_extends
    if nodelist.get_nodes_by_type(ExtendsNode):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 1011, in get_nodes_by_type
    nodes.extend(node.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 995, in get_nodes_by_type
    nodes.extend(nodelist.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 1011, in get_nodes_by_type
    nodes.extend(node.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 995, in get_nodes_by_type
    nodes.extend(nodelist.get_nodes_by_type(nodetype))
AttributeError: 'list' object has no attribute 'get_nodes_by_type'
```

i.e it seems that it tries to call get_nodes_by_type on a list (!)

However, if I create a file named `foo_partial.html`, put the above snippet inside that file and include it on my template using `{% include "foo_partial.html" %}` it works without problems! 

Please notice I didn't change anything else while upgrading to the new version, I only changed {% slot %} to {% fill %}. Can you please clarify what is the problem? 

BR,
Serafeim

### PR DESCRIPTION
**Pull request by spapas**
This PR fixes #239

### CODE REVIEW

**Review by lemontheme — CHANGES_REQUESTED** [review]
Good stuff. Small change request, since I prefer to address these sort of things at the source rather than reassign instance attributes.

How about we remove this statement but change self.fill_nodes in the ComponentNode.\_\_init\_\_ as follows...

```
self.fill_nodes: NodeList[FillNode] = NodeList()
```

That way, the code in this function requires no modifications and the fix propagates to other potential consumers of ComponentNode. (It seems to work when I test locally.)

With that done, I'll run the tests and get this fix out the door!

**Comment by spapas** [comment]
Hey @lemontheme I just tested it and it works great with the change you proposed so I updated the PR.

Thank you

**Review by lemontheme — APPROVED** [review]

**Comment by spapas** [comment]
@lemontheme thank you so much for the quick response and fix! Any idea when a new version with the fix will be released to pypi? For now I'm using `-e git+https://github.com/EmilStenstrom/django-components.git@master#egg=django_components`

Kind regards,
Serafeim

**Comment by lemontheme** [comment]
Done! Changes are available on 0.26.2. 🎉 Thanks for your help!

**Comment by EmilStenstrom** [comment]
Well researched and fixed! I'm thinking that we maybe should add a simple testcase for this bug (in a separate PR) too somewhere? Just so we don't accidentally break this case in the future? Did you manage to reproduce this spapas?

**Comment by spapas** [comment]
Hey @EmilStenstrom unfortunately I didn't have the time since it now works fine anyway !

I guess it would be useful to know what triggered it though, so I'll try to schedule a little time to research it the next days ⌛

**Comment by spapas** [comment]
Hello @EmilStenstrom and @lemontheme I've created a small repo that reproduces the problem: https://github.com/spapas/test_components

As I said in the comments for #239 it seems that the problem results when using `{% extends %}` on your template. So in `home.html` I've got a simple component that throws the exception when rendering:

```
Traceback (most recent call last):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\loader_tags.py", line 294, in do_extends
    if nodelist.get_nodes_by_type(ExtendsNode):
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 1011, in get_nodes_by_type
    nodes.extend(node.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 995, in get_nodes_by_type
    nodes.extend(nodelist.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 1011, in get_nodes_by_type
    nodes.extend(node.get_nodes_by_type(nodetype))
  File "C:\progr\py3\ehcg\venv\lib\site-packages\django\template\base.py", line 995, in get_nodes_by_type
    nodes.extend(nodelist.get_nodes_by_type(nodetype))
AttributeError: 'list' object has no attribute 'get_nodes_by_type'
```

**Comment by lemontheme** [comment]
Excellent! I was already planning on revisiting your last comment under the issue, but this is even better!

I'll incorporate these findings into a new regression test. ('extends' isn't used anywhere at the moment.)

@EmilStenstrom Once that's done, I'm going to review our tests to check that all Django builtin tags are used at least once in a non-failure test case, just to rule out other potential points of weakness.

**Comment by EmilStenstrom** [comment]
That sounds excellent! :)

**Pull request merged**
